language: c
script: meson -Db_sanitize=address . ./build --buildtype=debugoptimized && cd ./build && ninja
compiler: clang
env:
  - ASAN_OPTIONS=protect_shadow_gap=false

# Uncomment me if this gets annoying
#
# notifications:
#   email: false

before_install:
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip ninja-linux.zip
  - sudo mv ninja /usr/bin/
install:
  - pip3 install --user -I meson==0.44.1

addons:
  apt:
    packages:
    - python3
    - python3-pip
    - libgmp3-dev
    - libsigsegv-dev
    - openssl
    - libssl-dev
    - libncurses5-dev
    - automake
    - autoconf
    - make
    - libtool
    - g++
    - re2c
    - libcurl4-gnutls-dev
    - unzip
# before_deploy: "make deb" # TODO
deploy:
  skip_cleanup: true
  provider: releases
  prerelease: true # turn this off for official releases
  api_key:
    secure: V4E7784ECSS3MO6ZIRtang9XwibDyvDYGb0MoSaP2CTlmzIAhdokr4KJFM0qM4KRaaajCdQuqi0lojgOjwdxs7e0GkAwScb33LFxQ7Chj/QkFOY7V1AnSRLR5OsXnazB0nur5aSwvcvnggQ2XW3OeF7zIvGfs9aR97SEz/xCrVE=
  file: ./build/urbit # TODO upload package from before_deploy
  on:
    repo: urbit/urbit
    tags: true
